-
  name: "ping"
  hosts: all
  gather_facts: yes
  vars:
    Service_File_path: root/Ansible_output
  any_errors_fatal: true
  tasks:
    - include: tasks/preCheck.yml
    - include: tasks/reboot.yml
    - include: tasks/postCheck.yml
    - include: tasks/Compare.yml



-
  name: merge all the file in csv fail
  hosts: localhost
  vars:
    Service_File_path: root/Ansible_output
  tasks:
    - include: tasks/MergeFile.yml
    - include: tasks/SendMail.yml
