apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - targetPort: 8080   # POD port
      port: 80      #service port
      nodePort: 30009   # node port
  selector:
    type: front-end
